# Generated by Django 4.1.4 on 2023-02-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_board_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Rolle',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='modification_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
